services:
  site:
    extends:
      file: ./site/docker-compose.prod.yml
      service: site

  photo:

    extends:
      file: ./photo/docker-compose.prod.yml
      service: photo

networks:
  shared-network:
    driver: bridge
