version: '3.8'

services:
  site:
    build:
      context: ./site
    image: site:latest
    ports:
      - "3000:3000"
    networks:
      - shared-network

  photo:
    build:
      context: ./photo
    image: photo:latest
    ports:
      - "4000:4000"
    networks:
      - shared-network
    depends_on:
      - site
      
networks:
  shared-network:
    driver: bridge
