services:
  site:
    extends:
      file: ./site/docker-compose.prod.yml
      service: site

  redis:
    extends:
      file: ./site/docker-compose.prod.yml
      service: redis

  screenshot-taker:
    extends:
      file: ./screenshot-taker/docker-compose.prod.yml
      service: screenshot-taker

  screenshot-processer:
    extends:
      file: ./screenshot-processer/docker-compose.prod.yml
      service: screenshot-processer

  backend-orchestrator:
    extends:
      file: ./backend-orchestrator/docker-compose.prod.yml
      service: backend-orchestrator

networks:
  shared-network:
    driver: bridge

volumes:
  redis_data:
