services:
  site:
    extends:
      file: ./site/docker-compose.prod.yml
      service: site

  redis:
    extends:
      file: ./site/docker-compose.prod.yml
      service: redis

  photo:
    extends:
      file: ./photo/docker-compose.prod.yml
      service: photo

networks:
  shared-network:
    driver: bridge

volumes:
  redis_data: