services:
  screenshot-taker:
    extends:
      file: ./screenshot-taker/docker-compose.prod.yml
      service: screenshot-taker

  screenshot-processor:
    extends:
      file: ./screenshot-processor/docker-compose.prod.yml
      service: screenshot-processor

  backend-orchestrator:
    extends:
      file: ./backend-orchestrator/docker-compose.prod.yml
      service: backend-orchestrator

networks:
  default:
    name: screenshot-network
    external: true

volumes:
  redis_data:
