services:
  site-sender-common-builder:
    extends:
      file: ../common/docker-compose.dev.yml
      service: site-sender-common-builder

  screenshot-common-builder:
    depends_on:
      - site-sender-common-builder
    extends:
      file: ./common/docker-compose.dev.yml
      service: screenshot-common-builder

  screenshot-taker:
    depends_on:
      - screenshot-common-builder
    extends:
      file: ./screenshot-taker/docker-compose.dev.yml
      service: screenshot-taker

  screenshot-processor:
    depends_on:
      - screenshot-common-builder
    extends:
      file: ./screenshot-processor/docker-compose.dev.yml
      service: screenshot-processor

  backend-orchestrator:
    depends_on:
      - screenshot-common-builder
    extends:
      file: ./backend-orchestrator/docker-compose.dev.yml
      service: backend-orchestrator

networks:
  default:
    name: site-sender-network
    external: true

volumes:
  redis_data:
