services:
  photo:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: photo:latest
    environment:
      - NODE_ENV=production
      - SITE_URL=http://site:3000
    env_file:
      - .env
    ports:
      - "4000:4000"
