services:
  photo:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: photo:latest
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    restart: unless-stopped