services:
  photo:
    build:
      dockerfile: Dockerfile.dev
    image: photo:dev
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    ports:
      - "4000:4000"