version: '3.8'

services:
  photo:
    build:
      dockerfile: Dockerfile.dev
    image: photo:dev
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"