version: '3.8'

services:
  photo:
    build:
      dockerfile: Dockerfile.dev # Specify Dockerfile for the photo service in development mode
    image: photo:dev
    volumes:
      - ./src:/app/src # Assuming src is where your code lives
    environment:
      - NODE_ENV=development # Set the environment variable for development
    ports:
      - "4000:4000"