version: '3.8'

services:
  photo:
    build:
      dockerfile: Dockerfile.prod
    image: photo:latest
    environment:
      - NODE_ENV=production 
    env_file:
      - .env
    ports:
      - "4000:4000"
