services:
  screenshot-taker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: screenshot-taker:latest
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    restart: unless-stopped