version: '3.8'

services:
  site:
    build:
      dockerfile: Dockerfile.dev
    image: site:dev
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - FAST_REFRESH=false
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
