version: '3.8'

services:
  site:
    build:
      dockerfile: Dockerfile # Specify Dockerfile for the site service
    image: site:dev
    environment:
      - NODE_ENV=development # Set the environment variable for development
    ports:
      - "3000:3000"
