services:
  site:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: site:dev
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - FAST_REFRESH=false
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.dev
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    volumes:
      - pi-site-sender-redis_data:/data
    restart: unless-stopped

networks:
  default:
    name: site-sender-network
    external: true

volumes:
  pi-site-sender-redis_data:
