services:
  site-sender-common-builder:
    extends:
      file: ../common/docker-compose.prod.yml
      service: site-sender-common-builder

  site:
    depends_on:
      - site-sender-common-builder
      - redis
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: site:latest
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  redis:
    depends_on:
     - site-sender-common-builder
    image: redis:latest
    volumes:
      - pi-site-sender-redis_data:/data
    restart: unless-stopped

networks:
  default:
    name: site-sender-network
    external: true

volumes:
  pi-site-sender-redis_data:
