services:
  site-sender-common-builder:
    volumes:
      - ./dist:/app/dist
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: site-sender-common-builder:latest
    environment:
      - NODE_ENV=production