services:
  site-sender-common-builder:
    volumes:
      - ./dist:/app/dist
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: site-sender-common-builder:dev
    environment:
      - NODE_ENV=development
